### ISSUE TITLE
关于记录用户名密码功能

### ISSUE THREAD

**Issue by kathycxz** [Mzying2001/CefFlashBrowser#3]
在此谢谢大佬软件，本人工作单位需要用到flash上传文件，用着很开心，麻烦问一下能不能添加一个记录用户名密码的功能，毕竟领导的活还是要干，账号比较多，谢谢。

**Comment by Mzying2001** [comment]
CefSharp没有提供相应的接口，这个功能我暂时没有较好的实现的思路...

**Comment by iPixelOldC** [comment]
用keepassxc，全局快捷键呼出密码库，让他来填就完事了
（不嫌麻烦，在keepassxc标题栏，不同账号设置不同标题，内容根据你网页标题来填，毕竟不能装浏览器插件，不能靠浏览器提供必要的资料，如网址。然后他可以根据标题自动过滤出你要的账号集合）
