### ISSUE TITLE
无法启动cef

### ISSUE THREAD

**Issue by 1235789gzy1** [Mzying2001/CefFlashBrowser#33]
在事件查看器中有以下错误

应用程序: CefFlashBrowser.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.NullReferenceException
   在 CefFlashBrowser.App.InitCefFlash()
   在 CefFlashBrowser.App.OnStartup(System.Windows.StartupEventArgs)
   在 System.Windows.Application.<.ctor>b__1_0(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 System.Windows.Application.Run(System.Windows.Window)
   在 CefFlashBrowser.App.Main()

**Comment by Mzying2001** [comment]
看起来应该是读配置文件出问题了，你可以删除掉用户文档目录下的“CefFlashBrowser/Settings.json”文件再打开试试。
我在最近一次提交中处理了空引用的问题： 51e8060 ，如果上面的方法可以的话下个版本应该就没有这个问题了。

**Comment by 1235789gzy1** [comment]
> 看起来应该是读配置文件出问题了，你可以删除掉用户文档目录下的“CefFlashBrowser/Settings.json”文件再打开试试。 我在最近一次提交中处理了空引用的问题： [51e8060](https://github.com/Mzying2001/CefFlashBrowser/commit/51e8060801b758ccb3d948787b96f003dffaae80) ，如果上面的方法可以的话下个版本应该就没有这个问题了。

感谢，问题解决了
