### ISSUE TITLE
4399个别小游戏无法加载

### ISSUE THREAD

**Issue by fgr178707** [Mzying2001/CefFlashBrowser#39]
![image](https://github.com/Mzying2001/CefFlashBrowser/assets/109357981/68590076-923f-4a8a-8277-b805c73a39ef)
https://www.4399.com/flash/181657_4.htm

**Comment by Mzying2001** [comment]
这应该是4399的问题，解决方法详见
https://github.com/Mzying2001/CefFlashBrowser/discussions/19

**Comment by fgr178707** [comment]
> 这应该是4399的问题，解决方法详见 #19

感谢
