### ISSUE TITLE
 打不开

### ISSUE THREAD

**Issue by gcfthv** [Mzying2001/CefFlashBrowser#5]
双击CefFlashBrowser.exe没任何反应

**Comment by bryrnt** [comment]
一样双击没有反应啊 你解决了吗？

**Comment by lqzxlg** [comment]
运行环境win10 22H2，双击无反应，使用兼容模式和管理员启动也没有用

**Comment by chendingjun** [comment]
我也遇到了这样的问题，我一台电脑上装好后，双击无反应，尝试了兼容模式和管理员启动。另一台电脑打开后，点击了清除缓存，之后就再也打不开了。

**Comment by Mzying2001** [comment]
v1.0.7版本修复了配置文件导致打不开的bug，用新版本试试
https://github.com/Mzying2001/CefFlashBrowser/releases/latest
