### ISSUE TITLE
4399上那些Unity游戏貌似玩不了？

### ISSUE THREAD

**Issue by KahinHe** [Mzying2001/CefFlashBrowser#6]
4399上那些Unity游戏 提示要安装Unity插件 可是Unity的安装包安装完依旧提示要安装Unity插件 是这个浏览器装不了插件吗？

**Comment by Mzying2001** [comment]
4399上的那些Unity游戏用到的插件是NPAPI插件，CEF不支持这种插件，所以应该是不能在这个浏览器上玩这类游戏了

**Comment by oublie6** [comment]
U3D的直接用你自己装的chrome玩就行了，这个浏览器是专门用来玩flash游戏的
