### ISSUE TITLE
一些flash内容似乎被Chromium内核屏蔽，你 可以在SWF播放器中播放它；及QQ/微信无法正常登录问题

### ISSUE THREAD

**Issue by nanxun-sys** [Mzying2001/CefFlashBrowser#65]
当点开4399游戏客户端的时候依旧被检测需要flash插件，当点击swf播放器是出现白屏。

**Comment by nanxun-sys** [comment]
![Uploading bcc125c39dcc6fb365707f6b6d4606eb.png…](出现以上提示需要flash插件点击右上角“x”，等待几秒进入界面，岛登陆界面选择QQ/微信登陆会出现卡在登陆页面无法正常跳转，刷新页面直接进入正常游戏界面。至此问题全部解决。)

**Comment by oYovovovo** [comment]
没有“X”
